apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-flask-app
  name: my-flask-app
  namespace: default
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: pearlsprathap/example-image:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
