apiVersion: v1
kind: Service
metadata:
  name: {app_name}-flower
  namespace: {namespace}
  labels:
    app: {app_name}-flower
spec:
  type: NodePort
  ports:
  - port: 5555
    protocol: TCP
  selector:
    run: {app_name}-flower